name: notabilia
description: "A fully functional note taking app."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  shared_preferences: ^2.2.3
  iconsax: ^0.0.8
  sqflite: ^2.3.3+1
  intl: ^0.19.0
  path_provider: ^2.1.3
  pdf: ^3.11.0
  file_picker: ^8.0.6
  loading_animation_widget: ^1.2.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: ibmFont
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
    - family: arial
      fonts:
        - asset: assets/fonts/arial.ttf